[package]
name = "code"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"


[[bin]]
name = "code"
path = "code.rs"

[profile.release]
lto = true
strip = true
opt-level = 3
panic = "abort"
codegen-units = 1