[package]
name = "n_body_rs"
version = "0.1.0"
edition = "2021"

[dependencies]

[release.profile]
opt-level = 3

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
